# DOCKER-VERSION 1.10
FROM node:8.9.0
MAINTAINER xcyxiner "xcyxiner@me.com"
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN npm install -g strongloop
RUN npm install -g pm2
expose  3000
